import Head from 'next/head'

import Header from '../../components/header';
import styles from './projects.module.css';
import {createClient} from "next-sanity";

export default function Projects({pets}) {
  return (
    <div>
      <Head>
        <title>Henric \ Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <div className={styles.introText}>
            <div className={styles.introTitle}>
                PROJECTS
            </div>
            <div className={styles.introSubtitle}>
                Scroll down to see a selected set of projects I have worked on.
                </div>

        </div>
        {pets.length > 0 && (
          <ul>
            {pets.map((pet) => (
              <li key={pet._id}>{pet?.name}</li>
            ))}
          </ul>
        )}

      </div>
    </div>
  )
}
const client = createClient({
    projectId: "1q15ddoq",
  dataset: "production",
  apiVersion: "2022-05-11",
  useCdn: false
});

export async function getStaticProps() {
    const pets = await client.fetch(`*[_type =="pet"]`);
  
    return {
      props: {
        pets
      }
    };
  }
