import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header';
import Footer from '../components/footer';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Henric Zethraeus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
    
    <div className={styles.belowText}>
      <span>FULLSTACK</span>
      <span>DEVELOPER</span>
      </div>

    <div className={styles.frontImage}></div>
    <div className={styles.lowText}>
      <span>Based in</span>
      <span>Copenhagen</span>
    </div>
      </div>
      <Footer />
    </div>
  )
}
