import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/header';
import styles from './about.module.css';

export default function About() {
  return (
    <div>
      <Head>
        <title>Henric \ About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
     
    </div>
  )
}
